### ISSUE TITLE
In `buyQuery`: `createRequestOrder` does not expect a `callback` parameter

### ISSUE THREAD

**Issue by iosonopersia** [vaimee/desmo-sdk#5]
See documentation of iExec SDK: [IExecOrderModule:createRequestOrder](https://github.com/iExecBlockchainComputing/iexec-sdk/blob/master/docs/classes/IExecOrderModule.md#createrequestorder).

The `createRequestOrder` function does not expect to receive a `callback` parameter, so we need to check again the code of `buyQuery` in the `Desmo` module. We may simply need to remove [this line](https://github.com/vaimee/desmo-sdk/blob/ca15f82b2a9df8155036120fe1d5e5efea639776/src/lib/desmoContract-module.ts#L159).

**Comment by iosonopersia** [comment]
Experimentally done in PR #1 (commit b549641f8d4ede531157398ecb81e26336409eca).

**Comment by iosonopersia** [comment]
**Update**: removing the `callback` parameter causes the following error when calling `buyQuery`:

> Error: Requester storage token is not set for selected provider "ipfs". Result archive upload will fail.
>     at checkRequestRequirements (C:\Users\Simone\Documents\Github\desmo-sdk\node_modules\iexec\dist\common\execution\request-helper.js:103:13)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at IExecOrderModule.signRequestorder (C:\Users\Simone\Documents\Github\desmo-sdk\node_modules\iexec\dist\lib\IExecOrderModule.js:88:100)
>     at Desmo.buyQuery (C:\Users\Simone\Documents\Github\desmo-sdk\src\lib\desmo-module.ts:162:28)
>     at Context.<anonymous> (C:\Users\Simone\Documents\Github\desmo-sdk\src\test\desmo-test.ts:45:7)

**Comment by relu91** [comment]
The doc is probably outdated... check the internal docs: https://github.com/iExecBlockchainComputing/iexec-sdk/blob/e41d2c282d10d3cbd19a4d8f47dd8e4639891aca/docs/interfaces/internal_.RequestorderTemplate.md. However, I still have to figure out why the callback is needed... since we must retrieve the task result manually... We have to investigate more.

**Comment by iosonopersia** [comment]
I kept the `callback` parameter in #1 but this means I had to use a `@ts-ignore` comment. Let's keep this issue open until we fully understand how this function works.

**Comment by iosonopersia** [comment]
We are using v7.2.1 of iExec SDK. Here's the line at which the `callback` parameter gets used. It gets validated to be sure it's a proper hex address and it's then put in the returned data structure.

**Comment by relu91** [comment]
> We are using v7.2.1 of iExec SDK. Here's the line at which the `callback` parameter gets used: [see here](https://github.com/iExecBlockchainComputing/iexec-sdk/blob/4e5ea103c7dda50b0a6c665c7f1a725859f1a98f/src/common/market/order.js#L1031). It gets validated to be sure it's a proper hex address and then it's put in the returned data structure.

Related to [this comment](https://github.com/vaimee/desmo-sdk/issues/12#issuecomment-1237246037) (?) In particular, I'm referring to why we need the `verifyCallbackAddress` method.
